#define LOAD_VALUE 		1
#define LOAD_ADDRESS 	2
#define LOAD_IND 		3
#define LOAD_IDX_X 		4 
#define LOAD_IDX_Y 		5
#define LOAD_SP_X	 	6
#define STORE_ADDRESS	7
#define GET				8
#define PUT_PORT		9
#define ADD_X			10
#define ADD_Y			11
#define SUB_X			12
#define SUB_Y			13
#define COPY_TO_X		14
#define COPY_FROM_X		15
#define COPY_TO_Y 		15
#define COPY_FROM_Y		16
#define COPY_TO_SP		17
#define COPY_FROM_SP	18
#define JUMP_ADDRESS	19
#define JUMP_IF_EQUAL 	20
#define JUMP_IF_NOT_EQL	21
#define CALL_ADDRESS	23
#define RET				24
#define INCREMENT_X		25
#define DECREMENT_X		26
#define PUSH_AC			27
#define POP_AC			28
#define SYS_INT			29
#define IRET			30
#define END				50
 
